/**
 * Browser islands (vanilla JS, each < 2KB). Props always carry `base`, the
 * site prefix; the cart token lives in localStorage per base. All user
 * content is written with textContent, never innerHTML.
 */

/** Click [data-add] (or the root) to POST the product; reads qty from [data-qty]. */
export const ADD_TO_CART = `(el,p)=>{if(!p.product)return;const K='modulo_cart'+p.base,b=el.querySelector('[data-add]')||el,q=el.querySelector('[data-qty]'),m=el.querySelector('[data-msg]');b.addEventListener('click',async e=>{e.preventDefault();b.disabled=true;let t;try{t=localStorage.getItem(K)}catch(x){}try{const r=await fetch(p.base+'/_api/m/shop/cart/items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token:t||undefined,product:p.product,qty:q?Math.max(1,parseInt(q.value,10)||1):1})}),c=await r.json();if(!r.ok)throw new Error((c.error&&c.error.message)||c.message||'Could not add to cart');try{localStorage.setItem(K,c.token)}catch(x){}document.dispatchEvent(new CustomEvent('modulo:cart',{detail:c}));if(m)m.textContent=p.added||'Added to cart'}catch(x){if(m)m.textContent=x.message}finally{b.disabled=false}})}`;

/** Shows the cart item count in [data-count]; refreshes on modulo:cart. */
export const CART_BUTTON = `(el,p)=>{const K='modulo_cart'+p.base,c=el.querySelector('[data-count]'),s=n=>{c.textContent=n;el.classList.toggle('has-items',n>0)};document.addEventListener('modulo:cart',e=>s((e.detail&&e.detail.count)||0));let t;try{t=localStorage.getItem(K)}catch(x){}if(t)fetch(p.base+'/_api/m/shop/cart?token='+encodeURIComponent(t)).then(r=>r.json()).then(d=>s(d.count||0)).catch(()=>{})}`;

/** Full cart: lines with qty inputs and remove buttons, total, and the checkout form. */
export const CART = `(el,p)=>{const K='modulo_cart'+p.base,A=p.base+'/_api/m/shop',L=el.querySelector('[data-lines]'),T=el.querySelector('[data-total]'),F=el.querySelector('form'),M=el.querySelector('[data-msg]');let t;try{t=localStorage.getItem(K)}catch(x){}const m=v=>{try{return new Intl.NumberFormat(void 0,{style:'currency',currency:p.currency}).format(v)}catch(x){return(+v).toFixed(2)}},E=(g,c,x)=>{const n=document.createElement(g);if(c)n.className=c;if(x!=null)n.textContent=x;return n},R=async(u,o)=>{const r=await fetch(A+u,o&&{method:o.m,headers:{'content-type':'application/json'},body:JSON.stringify(o.b)}),d=await r.json();if(!r.ok)throw new Error((d.error&&d.error.message)||d.message||'Error');return d},U=(k,u,b)=>R(u,{m:k,b}).then(D).catch(e=>M.textContent=e.message),D=c=>{const it=c.items||[];if(c.token){t=c.token;try{localStorage.setItem(K,t)}catch(x){}}M.textContent='';L.replaceChildren();it.forEach(i=>{const r=E('div','shop-line'),q=E('input'),x=E('button','shop-rm','\\u00d7');q.type='number';q.min='0';q.value=i.qty;q.setAttribute('aria-label','Quantity');q.onchange=()=>U('PATCH','/cart/items/'+i.product,{token:t,qty:Math.max(0,parseInt(q.value,10)||0)});x.type='button';x.setAttribute('aria-label','Remove');x.onclick=()=>U('DELETE','/cart/items/'+i.product+'?token='+encodeURIComponent(t));r.append(E('span','shop-line-title',i.title),q,E('span','shop-line-total',m(i.line)),x);L.append(r)});if(!it.length)L.append(E('p','shop-empty',p.empty));T.textContent=it.length?m(c.total):'';F.hidden=!it.length;document.dispatchEvent(new CustomEvent('modulo:cart',{detail:c}))};F.onsubmit=async e=>{e.preventDefault();try{const d=await R('/checkout',{m:'POST',b:{token:t,email:F.email.value,base:p.base}});try{localStorage.removeItem(K)}catch(x){}location.href=d.redirect}catch(x){M.textContent=x.message}};t?R('/cart?token='+encodeURIComponent(t)).then(D).catch(()=>D({})):D({})}`;
