/** Templates for `modulo module new <name>`. */

export const NEW_MODULE_NAME_RE = /^[a-z][a-z0-9-]{1,30}$/;

function title(name: string) {
  return name
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}

export function moduleTemplate(name: string): Record<string, string> {
  const ns = name.replace(/-/g, '_');
  const label = title(name);
  const pkg = {
    name: `@modulo/mod-${name}`,
    version: '0.1.0',
    type: 'module',
    exports: { '.': './src/index.ts' },
    dependencies: { '@modulo/core': 'workspace:*', '@modulo/kernel': 'workspace:*' },
  };

  const index = `import { defineModule } from '@modulo/kernel';
import { defineBlock, defineModel, f, h, mf } from '@modulo/core';

/**
 * ${label}: a starter module with a model, a block and an API route.
 * See docs/MODULE-CONVENTIONS.md for the full contract.
 */
export default defineModule({
  name: '${name}',
  version: '0.1.0',
  label: '${label}',
  kernel: '^1.0.0',
  models: [
    defineModel({
      name: '${ns}.item',
      label: 'Item',
      titleField: 'title',
      fields: {
        title: mf.string({ required: true }),
        body: mf.text(),
        published: mf.boolean({ default: true }),
      },
      access: { read: 'public' },
      order: 'created_at desc',
    }),
  ],
  blocks: [
    defineBlock({
      type: '${name}:items',
      version: 1,
      label: '${label} items',
      category: '${label}',
      fields: {
        heading: f.text({ default: 'Latest items' }),
        limit: f.number({ default: 5, min: 1, max: 50 }),
      },
      load: async (props, { services }) => services.ctx.repo('${ns}.item').find({ where: { published: true }, limit: props.limit }),
      css: '.${ns}-items { padding: var(--space-md); } .${ns}-items h2 { color: var(--color-primary); }',
      render: (props, ctx) =>
        ctx.root(
          'section',
          { class: '${ns}-items' },
          h('h2', null, props.heading),
          h('ul', null, ...(ctx.data ?? []).map((item: any) => h('li', null, item.title))),
        ),
    }),
  ],
  routes: [
    {
      method: 'GET',
      path: '/items',
      surface: 'api',
      permission: 'public',
      handler: async ({ ctx }) => ({ body: await ctx.repo('${ns}.item').find({ where: { published: true } }) }),
    },
  ],
  permissions: [{ key: '${name}.manage', label: 'Manage ${label.toLowerCase()}' }],
  grants: { editor: ['${name}.manage'] },
  editor: { collections: [{ model: '${ns}.item', label: '${label}' }] },
});
`;

  const test = `import { describe, expect, it } from 'vitest';
import { createPgliteDb, invokeRoute, Kernel } from '@modulo/kernel';
import mod from '../src/index.ts';

describe('${name}', () => {
  it('stores items and serves published ones over the API', async () => {
    const kernel = await Kernel.create({ db: await createPgliteDb(), modules: [mod] });
    try {
      const site = await kernel.createSite({ slug: 'test', name: 'Test', modules: { '${name}': '*' } });
      const ctx = await kernel.context(site.id, null, { sudo: true });
      await ctx.repo('${ns}.item').create({ title: 'First' });
      await ctx.repo('${ns}.item').create({ title: 'Hidden', published: false });
      const res = await invokeRoute(ctx, { module: '${name}', method: 'GET', path: '/items' });
      expect((res.body as any[]).map((i) => i.title)).toEqual(['First']);
    } finally {
      await kernel.close();
    }
  });

  it('renders the items block', async () => {
    const block = mod.blocks![0]!;
    const html = JSON.stringify(
      block.render({ heading: 'Hi', limit: 5 }, { root: (tag: string, _a: unknown, ...children: unknown[]) => ({ tag, children }), data: [{ title: 'A' }] } as any),
    );
    expect(html).toContain('Hi');
    expect(html).toContain('A');
  });
});
`;

  const readme = `# ${label}

Modulo module \`${name}\`. Generated by \`modulo module new\`.

- \`src/index.ts\` — the module definition (model \`${ns}.item\`, block \`${name}:items\`, route \`GET /items\`)
- \`test/${name}.test.ts\` — run with \`npx vitest run modules/${name}\`
`;

  return {
    'package.json': JSON.stringify(pkg, null, 2) + '\n',
    'src/index.ts': index,
    [`test/${name}.test.ts`]: test,
    'README.md': readme,
  };
}
